nelmio_cors:
    defaults:
        origin_regex: false  # Changed to false for exact matching
        allow_credentials: true
        allow_origin: ['https://luie.raidvm.com']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_credentials: true
            allow_origin: ['https://luie.raidvm.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
